### PR TITLE
[Docs] Add logo to header in docs

### PR DESCRIPTION
**Pull request by jaredpalmer**
Was bored while on a conference call this morning...

- Adds React logo to header on desktop using an svg.
- Adds fidget-spinner like animation easter egg when you hover 🎉 

reason-react-fidget-spinner

### CODE REVIEW

**Comment by AgtLucas** [comment]
@jaredpalmer Awesome!

**Comment by chenglou** [comment]
Woah lol. Can you extract the css into its own file? The file's supposed to be shared across reason, reason-react and future projects.

**Comment by chenglou** [comment]
Merged. We're cool now!

**Comment by chenglou** [comment]
Spinner isn't working and misaligned after the change lol

**Comment by jaredpalmer** [comment]
See #24

**Comment by jaredpalmer** [comment]
I forgot a file lol

**Pull request merged**
