### PR TITLE
Add more svg css properties

### PR DESCRIPTION
**Pull request by AgtLucas**
Related to: #14 

Probably we are still missing some svg properties, though.

### CODE REVIEW

**Comment by glennsl** [comment]
There's a nice list of all the CSS properties in SVG 1.1 here: https://www.w3.org/TR/SVG/styling.html

**Comment by AgtLucas** [comment]
@glennsl Thanks! I'll update my PR asap!

**Comment by chenglou** [comment]
Thanks! Is it done?

**Comment by AgtLucas** [comment]
@chenglou I still need to add more properties, but feel free to merge it, I can open a new PR then. :)

**Comment by chenglou** [comment]
Thanks!

**Pull request merged**
