### PR TITLE
Remove dead domain https://mesopo.ai from user list

### PR DESCRIPTION
**Pull request by MoOx**
It leads to a parked domain now http://mesopo.ai (and https://mesopo.ai is scary on any modern browser)

poke @cullophid (original committer)

Cross posted from https://github.com/reasonml/reasonml.github.io/pull/518

### CODE REVIEW

**Comment by cullophid** [comment]
We had to close our company :(
Ill create a PR for Reason as well

**Comment by MoOx** [comment]
Sorry to heard that. I did the PR to reason already.

**Comment by Voronar** [comment]
> We had to close our company :(
> Ill create a PR for Reason as well

What the reason of closing? Not ReasonML?)

**Comment by cullophid** [comment]
No not ReasonML :)
We had a client back out of a signed contract right before our seed round. The contract was huge and we relied on it to sell our company to the investors so everything fell like a house if cards.

The timing had worked out so that all this happened just before we could start production on our sensor (main product of mesopo).
So we were caught without money and with out product and no way to start production.

**Comment by cullophid** [comment]
In my experience ReasonML is great for early stage startups. 
Before product market fit you are gonna make lots of huge changes to your code and a strong type system makes a huge difference.

Onboarding took ~ 1 week for a Js dev with typescript xp.

**Comment by chenglou** [comment]
Sorry to hear that. Good luck next time!

**Pull request merged**
