### PR TITLE
Adding Context

### PR DESCRIPTION
**Pull request by Hehk**
This is an initial attempt to bring the context API to reason-react. This version is implemented in pure Reason and does support working with react 15.

If React 15 support is no longer a priority I believe this can be done through a simple external on the ReactJS context API.

This code is a copy of a library I wrote: https://github.com/Hehk/reason-react-context

### CODE REVIEW

**Comment by Hehk** [comment]
`
[@bs.module "react"] external createContext : 'a => Js.Dict.t(ReasonReact.reactClass) = "";

module type ContextConfig = {type t; let debugName: string; let value: t;};

module CreateContext = (C: ContextConfig) => {
  let context = createContext(C.value);
  module Provider = {
    let make = (~value: C.t, children) =>
      ReasonReact.wrapJsForReason(
        ~reactClass=Js.Dict.unsafeGet(context, "Provider"),
        ~props={"value": value},
        children,
      );
  };
  module Consumer = {
    let make = (children: C.t => 'a) =>
      ReasonReact.wrapJsForReason(
        ~reactClass=Js.Dict.unsafeGet(context, "Consumer"),
        ~props=Js.Obj.empty(),
        children,
      );
  };
};
`

I messed around locally and this seems to work as an external (I am not the best at doing external so their might be a simpler way X.x)

**Comment by jaredly** [comment]
Thanks! This pure reason implementation has some behavioral differences to the react context api, which might be confusing. I'd probably vote to use the external to react 16, if we're willing to drop support for 15 (cc @chenglou). Otherwise, we could modify this PR to more closely match the react 16 behavior.

**Comment by chenglou** [comment]
Let's not reimplement it. My heuristics is "am I able to maintain this" lol

We'll drop 15 later

**Comment by jaredly** [comment]
Here's a simple wrapper of the react 16 context API if anyone wants it: https://gist.github.com/jaredly/951177b8f5518bfbd19aa1a5ce093e7b

**Comment by sslotsky** [comment]
@Hehk @jaredly have you thought about what updating should look like if your consumer is nested? In the [React docs](https://reactjs.org/docs/context.html#updating-context-from-a-nested-component) they create a component that wraps the provider, attaches update functions to the state, and passes in the state as the provider's value. If you wanted to do something similar, how would you do it? Maybe pass in a tuple containing the state and a record of update functions that delegate to `self.send`? How would something like that perform in terms of re-rendering?

**Comment by jaredly** [comment]
@sslotsky yup, you could basically use the same pattern they do

**Comment by sslotsky** [comment]
@jaredly Sure, except I don't think you can really attach the update handlers directly to the `state` object as they do in the example (or can you? Am I thinking about this wrong?) So it seems like you either have to provide a tuple or use some other form of composition. I'm wondering how that performs, because as I understand it, attaching the update handlers to the `state` object is done in order to retain referential identity for the value that gets passed to the provider, so that excessive re-rendering is avoided. Do I have that wrong?

**Comment by daniloraisi** [comment]
Using the same Context Binding from @jaredly, I created another example with complex context type for a themed bootstrap button: [https://gist.github.com/daniloraisi/6f76691c7f1d3d67f73a8506d34858f8](https://gist.github.com/daniloraisi/6f76691c7f1d3d67f73a8506d34858f8)

You can check a working Codesandbox too: [Reason Context API](https://codesandbox.io/s/pjj76x7o9q)

**Comment by grsabreu** [comment]
any news here?

**Comment by peterpme** [comment]
Hey @Hehk in an effort to clean up the repo, are you ok with closing this out and re-opening if its still valid?

Thanks!

**Comment by Hehk** [comment]
@peterpme No problem.

**Comment by peterpme** [comment]
Thanks! Closing this out for now :smile:

**Pull request closed without merging**
