### PR TITLE
RFC: simplify render & hydrate

### PR DESCRIPTION
**Pull request by bloodyowl**
Addresses #123

cc @chenglou @rickyvetter

### CODE REVIEW

**Comment by chenglou** [comment]
Thanks! Can't merge this yet; breaking change

**Comment by bloodyowl** [comment]
I can reimplement `withId` & `withClassName` in a light way using `"#" ++ selector` and `"." ++ selector` and create a `ReactDOMRe.rei` adding a deprecation notice on them if you like 😊

**Comment by bloodyowl** [comment]
oh right, `render` & `hydrate` signature are altered so it can't be retro-compatible 😅

**Comment by peterpme** [comment]
Hey @bloodyowl,

In an effort to clean this shizzle up, do you mind closing this out and re-opening if its still relevant? I _promise_ we'll be able to act on it faster :smile:

Thanks & sorry about the delay!!

**Comment by peterpme** [comment]
Closing this out for now :smile:

**Pull request closed without merging**
