### PR TITLE
Add note on children in jsx migration section

### PR DESCRIPTION
**Pull request by jchavarri**
I figure this out after some time today and thought it could be useful for others.

@rickyvetter Does this approach make sense? Do you think we should include other cases we've discussed? (like `ref` and how it has different types in v2 and v3)

### CODE REVIEW

**Comment by phated** [comment]
I like this but maybe it belongs in the documentation for `ReasonReactCompat` (which still needs to be written as per #372)

**Comment by jchavarri** [comment]
@phated thanks for the heads up. I wonder if the section on "migrating from jsx versions" should be included there too?

https://reasonml.github.io/reason-react/docs/en/jsx#migrating-from-version-2-to-version-3

It seems there is quite a lot of information around the migration that it deserves its own section, as the issue you posted suggests.

**Comment by rickyvetter** [comment]
@jchavarri any interest in making this new section? You can add in sidebars.json and then just make a new .md file. Also happy to merge this and then move it over!

**Comment by jchavarri** [comment]
@rickyvetter I've proposed the new section for `ReasonReactCompat` in #424 and moved the content from this PR over there, so closing! 🙂

**Pull request closed without merging**
