### PR TITLE
minor wording change to creation docs

### PR DESCRIPTION
**Pull request by thatbraxguy**
I noticed some awkward wording while reading through the docs. super minor 🐙

### CODE REVIEW

**Comment by chenglou** [comment]
Thanks. Should we just say "...asks you to return a component record, the one you created above"?

**Comment by thatbraxguy** [comment]
Going in that direction would "asks you to return the component record created above" work?

**Comment by chenglou** [comment]
Yep

**Comment by thatbraxguy** [comment]
updated

**Comment by chenglou** [comment]
Thanks!

**Pull request merged**
