### PR TITLE
Remove ReasonReact.createDomElement.

### PR DESCRIPTION
**Pull request by jdhorwitz**
Fixes issue https://github.com/reasonml/reason-react/issues/122

Removed ReasonReact.createDomElement.

### CODE REVIEW

**Comment by chenglou** [comment]
Sorry, I should have explained myself more clearly in the issue. `createDomElement` should be removed, but we need to fulfill its use-case better, otherwise we're literally removing an escape hatch =).

It'll probably be removed in the next next release, or so.

**Comment by cullophid** [comment]
@chenglou I assume the issue is `<div> ...children </div>` ?

**Comment by chenglou** [comment]
Lower-case desugared into a call that uses bs.splice, so they need an array literal. We did this out of care for perf. A few extra calls for each div didn't sound nice. I might have a few ways to circumvent these.

**Comment by cullophid** [comment]
can it not be handled by the JSX preprocessor?

**Comment by chenglou** [comment]
It can. We'll likely do that. Just that it's quite a bit of stuff in the JSX already. But yeah

**Comment by cullophid** [comment]
@chenglou true but then you dont have to do it at runtime.

**Comment by tmepple** [comment]
I've worked around this by using React fragments.  First by defining the external:

```
module Fragment = {
  [@bs.module "react"] external reactClass : ReasonReact.reactClass = "Fragment";
  let make = children =>
    ReasonReact.wrapJsForReason(~reactClass, ~props=Js.Obj.empty(), children);
};
```

Then just `<Fragment> ...children </Fragment>`

I'm not sure if it's as efficient as `createDomElement` or if there are other downsides but it works well without creating an extra `<div>`!

**Comment by peterpme** [comment]
Hey @jdhorwitz in an effort to clean up the repo, are you ok with closing this out and re-opening if its still valid?

**Comment by rickyvetter** [comment]
I don't think that this is relevant for the new JSX. This function will get deprecated with the rest of ReasonReact. Thanks for the discussion and sorry for the slow movement here.

**Pull request closed without merging**
