### PR TITLE
Make sure opam files have the same shape as opam repository after PR

### PR DESCRIPTION
**Pull request by davesnx**
Updating opam files after https://github.com/ocaml/opam-repository/pull/24422/files

Thanks @haochenx

### CODE REVIEW

**Comment by anmonteiro** [comment]
TBH I don't think this is necessary. We can just strip `@runtest` when releasing to opam. That's what I do in some of my packages too.

Doesn't justify having `.opam.template` files in the repo IMO.

**Comment by davesnx** [comment]
What's the problem with the opam template? I added to avoid the manual work on each release, which is rather annoying

**Comment by haochenx** [comment]
(since I'm pinged, allow me to add my two cents)

It's probably better (and safer?) to let Dune automatically generate the build command. I think @anmonteiro means stripping `@runtest` is probably a trivial diff to lose the benefits of having the Dune generated build commands.

Also, if the approach in https://github.com/ocaml/opam-repository/pull/24422/files#r1325843840 is adopted, then the stripping should not be necessary anymore.

(btw sadly the `@runtest` is hardcoded in Dune for now. ref: https://github.com/ocaml/dune/blob/main/src/dune_rules/opam_create.ml)

**Comment by davesnx** [comment]
That makes a lot of sense. Will try to use `{post}` on the next release and avoid the templates

**Comment by haochenx** [comment]
> Will try to use {post} on the next release

Just for your information: you can indeed open an PR to opam-repository to modify the current version to test whether `{post}` works now. opam-repository can take amendments to existing packages (and we see chose "maintenance" patches quite often)

**Pull request closed without merging**
