### PR TITLE
Add didCatch support

### PR DESCRIPTION
**Pull request by bloodyowl**
cc @rickyvetter

### CODE REVIEW

**Comment by mscharley** [comment]
Looks like a solution for #273 . What's needed to get this through?

**Comment by MoOx** [comment]
@bloodyowl care to resolve conflict?

Would be nice to have this lifecycle method!

**Comment by MoOx** [comment]
@bloodyowl mind updating the pr to avoid conflicts?

**Comment by bloodyowl** [comment]
unsure if it's worth it given the upcoming release. would this even work with the compat mode @rickyvetter?

**Comment by shulhi** [comment]
@bloodyowl what's going to happen in the upcoming release?

**Comment by rickyvetter** [comment]
Upcoming release will support the React hooks api. This will still work with interop, but we would like to get support for ErrorBoundaries in hooks to be able to support in our new API as well.

**Comment by bloodyowl** [comment]
@rickyvetter should I make a new PR that targets the `hooks` branch?

**Comment by zgavin1** [comment]
Any update on this? Do we just need to fix conflicts?

**Comment by flash-gordon** [comment]
@zgavin1 I don't think this will be merged, reason-react migrated to functional-style components and hooks, it's a perfect match for Reason. The legacy API will stay for a while but will eventually be removed. So far, there is [no hook equivalent](https://reactjs.org/docs/hooks-faq.html#do-hooks-cover-all-use-cases-for-classes) for `didCatch` but once it's there, I bet, adding support to reason-react will follow soon.

**Comment by peterpme** [comment]
Hey @bloodyowl 

Mind updating this branch? It will help wrt merging into master, thanks!!!

**Comment by bloodyowl** [comment]
@peterpme As the old API has been deprecated, I'll close this for now. Let's wait for React to officially release a functional way to handle this. In the meantime people can still import a JS class that handles this with FFI.

**Pull request closed without merging**
