### PR TITLE
Added Gain to Projects using reason-react

### PR DESCRIPTION
**Pull request by cullophid**
https://gain.ai is a product from https://sentia.ai

### CODE REVIEW

**Comment by cullophid** [comment]
We are using ReasonML /ReasonReact for our two react-native apps (currently in beta)

**Comment by cristianoc** [comment]
@cullophid can you check how the logo looks on the page?

**Comment by cullophid** [comment]
https://reasonml.github.io/reason-react/
Tiny :)
Do you need a new logo, or can you scale it?

**Comment by cristianoc** [comment]
@chenglou

**Comment by chenglou** [comment]
Ehm yeah, can we have a bigger logo please? Thanks =)

**Pull request merged**
